# Generated by Django 4.2 on 2023-04-11 03:41

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
