# Generated by Django 4.2 on 2023-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_commentaire_commentaire_alter_post_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=models.TextField(),
        ),
    ]
