# Generated by Django 4.2 on 2023-04-11 07:22

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
