# Generated by Django 4.2 on 2023-04-11 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
