# Generated by Django 4.0.3 on 2023-02-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(default='logo_emedia-com.png', upload_to='services')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('obs', 'Obsolète'), ('actu', 'Actualité')], default='actu', max_length=50)),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='avis/avatar-default.png', upload_to='avis')),
                ('nom', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=200)),
                ('avis', models.TextField(default='Avis positifs')),
                ('status', models.CharField(choices=[('obs', 'Obsolète'), ('actu', 'Actualité')], default='actu', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temoignage',
            },
        ),
    ]
