# Generated by Django 4.0.3 on 2023-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='services/logo_emedia-com.png', upload_to='services'),
        ),
    ]
