# Generated by Django 4.0.3 on 2023-02-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Catégorie de portfolios',
            },
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('image', models.ImageField(default='images/logo/logo_emedia-com.png', upload_to='galeries')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('obs', 'Obsolète'), ('actu', 'Actualité')], default='actu', max_length=50)),
                ('categorie_gal', models.ManyToManyField(related_name='categorie_gal', to='portfolio.categorieportfolio')),
            ],
            options={
                'verbose_name': 'Portfolio',
            },
        ),
    ]
