# Generated by Django 4.0.3 on 2023-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolios_categorie_gal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Catégorie de portfolio',
            },
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='categorie_gal',
        ),
        migrations.AddField(
            model_name='portfolios',
            name='categorie_gal',
            field=models.ManyToManyField(related_name='categorie_gal', to='portfolio.categorieportfolio'),
        ),
    ]
