# Generated by Django 4.0.3 on 2023-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_portfolios_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='nom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
